Assignment 05/Models/TempUser.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace Assignment_05.Models
{
    public class TempUser
    {
        [Required(ErrorMessage = "User Name Required")]
        public String Name { get; set; }

        [Required(ErrorMessage = "Email Required")]
        [DataType(DataType.EmailAddress, ErrorMessage = "Not an Email Format")]
        public String Email { get; set; }

        [Required(ErrorMessage = "Password Required")]
        public String Password { get; set; }

        [Required(ErrorMessage = "Confirmed Password Required")]
        [Compare("Password", ErrorMessage = "Confirm password doesn't match")]
        public String Password2 { get; set; }
    }
}

Assignment 05/Controllers/DBManagerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DAL.Models;

namespace Assignment_05.Controllers
{
    public class DBManagerController : Controller
    {
        UserDBEntities db = new UserDBEntities();
        // GET: DBManager
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Display()
        {
            return View(db.Users.ToList());
        }
    }
}

Assignment 05/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Assignment_05.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Assignment 05/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Policy;
using System.Web;
using System.Web.Mvc;
using Assignment_05.Models;
using DAL.Models;
using BLL;
using System.Runtime.CompilerServices;

namespace Assignment03.Controllers
{
    public class UserController : Controller
    {
        // GET: User
        public ActionResult Register()
        {
            TempUser tmp_u = new TempUser();
            tmp_u.Name = Request.Form["UserName"];
            tmp_u.Email = Request.Form["email"];
            tmp_u.Password = Request.Form["Password"];
            return View(tmp_u);
        }

        [HttpPost]
        public ActionResult Register(TempUser tmp_u)
        {
            if (ModelState.IsValid)
            {
                Users user = new Users();
                user.Name = tmp_u.Name;
                user.Email = tmp_u.Email;
                user.Password = tmp_u.Password;
                int res = new BLLClass().AddUser_BLL(user);
                return View("Confirmation",user);
            }
            return View();
        }

        [HttpPost]
        public ActionResult Confirmation(Users user)
        {
            return View();
        }
    }
}

Assignment 05/Views/DBManager/Display.cshtml
@model IEnumerable<DAL.Models.Users>

@{
    ViewBag.Title = "Display";
}

<h2>Display</h2>

<p>
    @Html.ActionLink("Create New", "Register","User")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Password)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Password)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>

Assignment 05/Views/DBManager/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2><br>
<li>@Html.ActionLink("Click Here to Display All Users", "Display", "DBManager")</li>

Assignment 05/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Assignment 05/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Assignment 05/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Assignment 05/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Sign Up", "Register", "User")</li>
                    <li>@Html.ActionLink("Go To DBManager", "Index", "DBManager")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Assignment 05/Views/User/Confirmation.cshtml
@model DAL.Models.Users 

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="@Url.Content("~/Content/StyleSheet1.css")" rel="stylesheet" type="text/css" />
    <title>Please Confirm Your Information: </title>
</head>
<body>
    <div>
        <table>
            <tr>
                <th> </th>
                <td>
                    <h5>Image Preview</h5><br>
                    <img class="headshot" id="image_prev" src="#" /><br>
                    <h5>Your Profile Pic</h5>
                    <input type="file" id="user_image" name="user_image" accept="image">
                </td>
            </tr>
            <tr>
                <th>User Name: </th>
                <td>
                    @Model.Name;
                </td>
            </tr>
            <tr>
                <th>Email Address: </th>
                <td>
                    @Model.Email;
                </td>
            </tr>
            <tr>
                <th>Password: </th>
                <td>
                    @Model.Password;
                </td>
            </tr>
        </table>
        
    </div>
    <script>
            user_image.onchange = evt => {
                const [file] = user_image.files
                if (file) {
                    image_prev.src = URL.createObjectURL(file)
                }
            }
    </script>
</body>
</html>

Assignment 05/Views/User/Register.cshtml
@model Assignment_05.Models.TempUser

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    @Styles.Render("~/Content/css")
    <title>Register as User</title>
</head>
<body>
    <div style="padding: 20px; width: 600px; height: 400px; ">
        @using (Html.BeginForm())
        {
            <table>
                <tr>
                    <th> </th>
                    <td>
                        <h5>Image Preview</h5><br>
                        <img class="headshot" id="image_prev" src="#" /><br>
                        <h5>Your Profile Pic</h5>
                        <input type="file" id="user_image" name="user_image" accept="image">
                    </td>
                </tr>
                <tr>
                    <th>@Html.Label("User Name: ")</th>
                    <td>
                        @Html.TextBoxFor(model => model.Name, new { placeholder = "User Name", @class = "form-input" })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </td>
                </tr>
                <tr>
                    <th>@Html.Label("Email Address: ")</th>
                    <td>
                        @Html.TextBoxFor(model => model.Email, new { placeholder = "Email Id", @class = "form-input" })
                        @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                    </td>
                </tr>
                <tr>
                    <th>@Html.Label("Password: ")</th>
                    <td>
                        @Html.PasswordFor(model => model.Password, new { placeholder = "Password", @class = "form-input" })
                        @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                    </td>
                </tr>
                <tr>
                    <th>@Html.Label("Confirmed Password: ")</th>
                    <td>
                        @Html.PasswordFor(model => model.Password2, new { placeholder = "Confirmed Password", @class = "form-input" })
                        @Html.ValidationMessageFor(model => model.Password2, "", new { @class = "text-danger" })
                    </td>
                </tr>
            </table>
            <button type="submit" class="btn-primary" style="float:right; border-radius: 10%">Submit</button>
        }
        <script>
            user_image.onchange = evt => {
                const [file] = user_image.files
                if (file) {
                    image_prev.src = URL.createObjectURL(file)
                }
            }
        </script>
    </div>
</body>
</html>